class TsolToPronunciation():
    def __init__(self):
        self.base_map = {
            # Multi
            'qσ': 'qu',
            'зw': '(è)sv',
            'зф': '(è)sf',
            'зп': '(è)sp',
            'зð': '(è)sd',
            'зr': '(è)sr',
            'ec': 'ès',
            'ßt': 'st(è)t',
            'ßŧ': 'st(è)ts',
            'Ϡḡ': 'j(è)jh',
            'cq': 'k',
            'öo': 'o(w)o',
            'æn': 'eaun',
            'œn': 'on',
            'oσ': 'ou',
            'kc': 'x',
            'иŋ': 'yèn',
            'ие': 'y',
            'ḳч': 'khch',
            'ḡч': 'ghch',
            'qk': 'kk',
            'ðз': 'ds',
            # Single
            'a': 'a',
            'æ': 'an',
            'ð': 'd',
            'o': 'o',
            'ö': 'ow',
            't': 't',
            'ŧ': 'ts',
            'e': 'e',
            'ẽ': 'è',
            'п': 'p',
            'ψ': 'ps',
            'ф': 'f',
            'з': 'z',
            'σ': 'u',
            'g': 'g',
            'ḡ': 'jh',
            'и': 'i',
            'ӣ': 'ain',
            'ß': 'st',
            'б': 'b',
            'c': 's',
            'r': 'r',
            'w': 'w',
            'ŵ': 'v',
            'ϡ': 'j',
            'k': 'k',
            'ḳ': 'kh',
            'ſ': 'h',
            'q': 'q',
            'm': 'm',
            'n': 'n',
            'ր': 'gn',
            'ը': 'hn',
            'ø': 'oh',
            'л': 'l',
            'ԓ': 'll',
            'ч': 'ch',
            'ŋ': 'èn',
            'œ': 'en'
        }
        
        self.vocal_map = {
            # Multi
            'qσ': 'qu',
            'зw': 'èsv',
            'зф': 'èsf',
            'зп': 'èsp',
            'зð': 'èsd',
            'зr': 'èsr',
            'ec': 'ès',
            'ßt': 'stèt',
            'ßŧ': 'stèts',
            'Ϡḡ': 'jèjh',
            'cq': 'k',
            'öo': 'owo',
            'æn': 'aun',
            'œn': 'on',
            'oσ': 'ou',
            'kc': 'x',
            'иŋ': 'yèn',
            'ие': 'y',
            'ḳч': 'khch',
            'ḡч': 'ghch',
            'qk': 'kk',
            'ðз': 'ds',
            # Special
            't ': 'te ',
            'in': 'ïhn',
            'ge': 'gué',
            # Single
            'a': 'ä',
            'æ': 'an',
            'ð': 'd',
            'ö': 'ow',
            'o': 'ö',
            't': 't',
            'ŧ': 'ts',
            'e': 'ë',
            'ẽ': 'è',
            'п': 'p',
            'ψ': 'ps',
            'ф': 'f',
            'з': 'z',
            'σ': 'ü',
            'g': 'gu',
            'ḡ': 'jh',
            'и': 'ï',
            'ӣ': 'ain',
            'ß': 'st',
            'б': 'b',
            'c': 's',
            'r': 'r',
            'w': 'w',
            'ŵ': 'v',
            'ϡ': 'j',
            'k': 'k',
            'ḳ': 'kh',
            'ſ': 'h',
            'q': 'q',
            'm': 'm',
            'ր': 'gn',
            'ը': 'hn',
            'n': 'n',
            'ø': 'oh',
            'л': 'l',
            'ԓ': 'y',
            'ч': 'ch',
            'ŋ': 'èn',
            'œ': 'en',
            # Special
            'gum': 'gm',
            'gur': 'gr',
            'gud': 'gd',
            'gun': 'gn',
            'gub': 'gb',
            'è': 'e',
            'y': 'ïe',
            'ïeen': 'ïèn',
            'guhsh': 'jhesh',
            'gu ': 'g ',
            'pz': 'ps',
            'enld': 'èld',
            'të ': 't ',
            'tsek': 'sek'
        }

    def translate(self, text: str, vocal_mode: bool=False) -> str:
        text_lower = text.lower().replace("ς", "σ") + " "
        if vocal_mode:
            for find, rep in self.vocal_map.items():
                text_lower = text_lower.replace(find.lower(), rep.lower())
        else:
            for find, rep in self.base_map.items():
                text_lower = text_lower.replace(find.lower(), rep.lower())
        return text_lower.strip()
